### ISSUE TITLE
Unable to Install for Python 2.7

### ISSUE THREAD

**Issue by foats** [luqasz/librouteros#13]
Trying to install on a server that only runs Python 2.7, fails with following output.

Collecting librouteros
  Using cached librouteros-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5YgwAy/librouteros/setup.py", line 62, in <module>
        'Topic :: Software Development :: Libraries'
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=12.0.5'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5YgwAy/librouteros/

**Comment by luqasz** [comment]
`pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), `
Do you have pinned setuptools to some other version ? 
How do you install librouteros ?

**Comment by foats** [comment]
@luqasz pip install -U setuptools fixed my issue - sorry for the inconvience.

**Comment by luqasz** [comment]
no problem.
