### ISSUE TITLE
Can't Import file

### ISSUE THREAD

**Issue by luisvalleGH** [luqasz/librouteros#226]
I want to import a file, what i found is that this particular command requires 2 sends

/import
=file-name=myscript.rsc
Requires two sends. The "/import" should be sent without the terminating zero. The "=filename=myscript.rsc" send should have the terminating zero.

I can't figure out how to do this with the library.

**Comment by luqasz** [comment]
What error did you get from librouteros ?

**Comment by luisvalleGH** [comment]
This is the code i'm using, I've tried different approaches, like using `/import` and algo using `=file_name=script_name`

```Python
        api = connect(username=username, password=password, host=host)
        
        path = api.path('')

        script_name = 'SNMP.rsc'
        response = tuple(path('import', file_name=script_name))
        
        return {"response": response}
```

Catching the error y got

```json
{
  "detail": "Mikrotik Trap Error: unknown parameter"
}
```

If i don't catch the error this is the console output log

```log
2023-11-13 11:03:54 INFO:     172.20.0.1:47986 - "POST /Mikrotik/UploadScript HTTP/1.1" 500 Internal Server Error
2023-11-13 11:03:54 ERROR:    Exception in ASGI application
2023-11-13 11:03:54 Traceback (most recent call last):
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2023-11-13 11:03:54     result = await app(  # type: ignore[func-returns-value]
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-13 11:03:54     return await self.app(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
2023-11-13 11:03:54     await super().__call__(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
2023-11-13 11:03:54     await self.middleware_stack(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-13 11:03:54     raise exc
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-13 11:03:54     await self.app(scope, receive, _send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-13 11:03:54     raise exc
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-13 11:03:54     await self.app(scope, receive, sender)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-13 11:03:54     raise e
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-13 11:03:54     await self.app(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
2023-11-13 11:03:54     await route.handle(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
2023-11-13 11:03:54     await self.app(scope, receive, send)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
2023-11-13 11:03:54     response = await func(request)
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
2023-11-13 11:03:54     raw_response = await run_endpoint_function(
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2023-11-13 11:03:54     return await dependant.call(**values)
2023-11-13 11:03:54   File "/app/routers/Mikrotik.py", line 44, in upload_mikrotik_script
2023-11-13 11:03:54     response = tuple(path('import', file_name=script_name))
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/librouteros/api.py", line 110, in __call__
2023-11-13 11:03:54     yield from self.api(
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/librouteros/api.py", line 35, in __call__
2023-11-13 11:03:54     yield from self.readResponse()
2023-11-13 11:03:54   File "/usr/local/lib/python3.9/site-packages/librouteros/api.py", line 76, in readResponse
2023-11-13 11:03:54     raise traps[0]
2023-11-13 11:03:54 librouteros.exceptions.TrapError: unknown parameter
```

**Comment by luqasz** [comment]
Try this. 
```
        api = connect(username=username, password=password, host=host)
        response = tuple(api('/import', file_name='SNMP.rsc'))

        return {"response": response}
```

**Comment by luisvalleGH** [comment]
> Try this.
> 
> ```
>         api = connect(username=username, password=password, host=host)
>         response = tuple(api('/import', file_name='SNMP.rsc'))
> 
>         return {"response": response}
> ```
Same error
```json
{
  "detail": "Mikrotik Trap Error: unknown parameter"
}
```

**Comment by luqasz** [comment]
It's `file_name` not `file-name`

**Comment by luisvalleGH** [comment]
The parameter is file-name, but nothing works, either file_name or file-name. Do you have an example that is working to you?

**Comment by luqasz** [comment]
This works
```python
api('/import', **{'file-name':'example.rsc'})
```

**Comment by luisvalleGH** [comment]
> This works
> 
> ```python
> api('/import', **{'file-name':'example.rsc'})
> ```

Yes! now the file is imported correctly, I need to figure out how to show the output, but that's another issue. Thanks!

```python
response = api('/import', **{'file-name':'SNMP.rsc'})

return {"response": response}
```
