### ISSUE TITLE
librouteros.exceptions.ConnectionError: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:661)

### ISSUE THREAD

**Issue by shuu01** [luqasz/librouteros#34]
OpenSSL 1.1.0f  25 May 2017

python -V
`Python 2.7.13`

```
import ssl
from librouteros import connect

def main(args):

    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    ctx.set_ciphers('ADH')
    api = connect(username='admin', password='password', host='host.domain', 
    ssl_wrapper=ctx.wrap_socket, port=8729)

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
```

```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    sys.exit(main(sys.argv))
  File "test.py", line 34, in main
    api = connect(username='admin', password='password', host='host.domain', ssl_wrapper=ctx.wrap_socket, port=8729)
  File "/home/pi/.local/lib/python2.7/site-packages/librouteros/__init__.py", line 41, in connect
    transport = create_transport(host, **arguments)
  File "/home/pi/.local/lib/python2.7/site-packages/librouteros/__init__.py", line 69, in create_transport
    raise ConnectionError(error)
librouteros.exceptions.ConnectionError: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:661)

```

with python3 works as expected

**Comment by luqasz** [comment]
What operating system are you running ?
