### ISSUE TITLE
[SSL: NO_CIPHERS_AVAILABLE] Python 3.5.3

### ISSUE THREAD

**Issue by gil-obradors** [luqasz/librouteros#37]
Proceding as wiki to make SSL connection to routerOS **6.42.6** : 
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> from librouteros import connect
>>> ctx = ssl.create_default_context()
>>> ctx.check_hostname = False
>>> ctx.verify_mode = ssl.CERT_NONE
>>> ctx.set_ciphers('ADH')
>>> api = connect(username='***************', password='************', host='10.228.5.50', ssl_wrapper=ctx.wrap_socket, port=8729)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/librouteros/__init__.py", line 66, in create_transport
    sock = kwargs['ssl_wrapper'](sock)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/librouteros/__init__.py", line 41, in connect
    transport = create_transport(host, **arguments)
  File "/usr/local/lib/python3.5/dist-packages/librouteros/__init__.py", line 69, in create_transport
    raise ConnectionError(error)
librouteros.exceptions.ConnectionError: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:720)
```

**Comment by luqasz** [comment]
https://librouteros.readthedocs.io/en/latest/usage.html#connecting
