### ISSUE TITLE
UnicodeDecode Error retriving  leases from dhcp server 

### ISSUE THREAD

**Issue by gil-obradors** [luqasz/librouteros#71]
I 'm trying to get all dhcp leases from a MK with version 6.45.2
Actually 3234 items,
```
lease_list  = [f for f in api(cmd='/ip/dhcp-server/lease/print')]
```
returns
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 11: ordinal not in range(128)
```

[f for f in api(cmd='/ip/dhcp-server/lease/print')]

pseudo-works, returns something strange, only 2313 leases, and the first truncated

My knowledges don't permit to enter in more depth,

The same requests to a 6.45.1 and 113 leases works fine

Here the complete traceback 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <listcomp>
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/api.py", line 28, in __call__
    yield from self.readResponse()
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/api.py", line 60, in readResponse
    reply_word, words = self.readSentence()
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/api.py", line 46, in readSentence
    reply_word, words = self.protocol.readSentence()
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/protocol.py", line 189, in readSentence
    sentence = tuple(word for word in iter(self.readWord, ''))
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/protocol.py", line 189, in <genexpr>
    sentence = tuple(word for word in iter(self.readWord, ''))
  File "/home/gil/PycharmProjects/testestest/venv/lib/python3.6/site-packages/librouteros/protocol.py", line 206, in readWord
    return word.decode(encoding=self.encoding, errors='strict')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 11: ordinal not in range(128)
```

If I can contribute with more data, here I'm

Thank you!

**Comment by gil-obradors** [comment]
I have found  more info:
The problem is a dhcp lease with a ®ROUTER® hostname:

Print from console:
```
Flags: X - disabled, R - radius, D - dynamic, B - blocked 
 #   ADDRESS                                       MAC-ADDRESS       HOST-NAME    SERVER    RATE-LIMIT    STATUS 
 0   217.150.214.79                                64:D1:54:F7:C6:B6 \AEROUTER\AE dhcp-data               waiting
```

From winbox

![imatge](https://user-images.githubusercontent.com/6016929/70142368-5b8d0f80-1699-11ea-93bb-3324697b95c2.png)

**Comment by luqasz** [comment]
Try passing a different `encoding` to `connect()`. Default is `ASCII`
https://github.com/luqasz/librouteros/blob/master/librouteros/__init__.py#L18

**Comment by gil-obradors** [comment]
Ok I haven't seen, thank you!

Congratulations for your work!
